# Generated by Django 3.1.1 on 2021-01-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClotherCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.IntegerField(unique=True)),
                ('size_name', models.CharField(max_length=255)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_clothes.sizecategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryClother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255)),
                ('subcategory_id', models.IntegerField(unique=True)),
                ('menclother_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_clothes.clothercategory')),
            ],
        ),
        migrations.CreateModel(
            name='CustomStyleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=255)),
                ('item', models.ManyToManyField(to='generate_clothes.SubCategoryClother')),
            ],
        ),
    ]
