# Generated by Django 3.1.1 on 2021-01-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothescategory',
            name='gender',
        ),
        migrations.AddField(
            model_name='clothessubcategory',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothessubcategory',
            name='season',
            field=models.CharField(choices=[('W', 'Winter'), ('S', 'Summer'), ('U', 'Universal')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
