# Generated by Django 3.1.1 on 2021-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstylecategory',
            name='item',
            field=models.ManyToManyField(related_name='item', to='generate_clothes.SubCategoryClother'),
        ),
    ]
