# Generated by Django 3.1.5 on 2021-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0002_auto_20210125_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrysettings',
            options={'verbose_name_plural': 'Country settings'},
        ),
        migrations.AlterField(
            model_name='clothescategory',
            name='category_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clothessubcategory',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='clothessubcategory',
            name='season',
            field=models.CharField(choices=[('W', 'Winter'), ('S', 'Summer'), ('U', 'Universal')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='clothessubcategory',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
