# Generated by Django 3.1.1 on 2021-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0002_auto_20210104_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstylecategory',
            name='jacket',
            field=models.ManyToManyField(related_name='jacket', to='generate_clothes.SubCategoryClother'),
        ),
    ]
