# Generated by Django 3.1.1 on 2021-01-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0003_customstylecategory_jacket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstylecategory',
            name='item',
        ),
        migrations.AddField(
            model_name='customstylecategory',
            name='hodie',
            field=models.ManyToManyField(related_name='hodie', to='generate_clothes.SubCategoryClother'),
        ),
        migrations.AddField(
            model_name='customstylecategory',
            name='pants',
            field=models.ManyToManyField(related_name='pants', to='generate_clothes.SubCategoryClother'),
        ),
        migrations.AddField(
            model_name='customstylecategory',
            name='shirt',
            field=models.ManyToManyField(related_name='shirt', to='generate_clothes.SubCategoryClother'),
        ),
        migrations.AddField(
            model_name='customstylecategory',
            name='shoes',
            field=models.ManyToManyField(related_name='shoes', to='generate_clothes.SubCategoryClother'),
        ),
    ]
