# Generated by Django 3.1.1 on 2021-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0004_auto_20210104_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstylecategory',
            name='hodie',
        ),
        migrations.RemoveField(
            model_name='customstylecategory',
            name='jacket',
        ),
        migrations.RemoveField(
            model_name='customstylecategory',
            name='pants',
        ),
        migrations.RemoveField(
            model_name='customstylecategory',
            name='shirt',
        ),
        migrations.RemoveField(
            model_name='customstylecategory',
            name='shoes',
        ),
        migrations.AddField(
            model_name='customstylecategory',
            name='item',
            field=models.ManyToManyField(related_name='item', to='generate_clothes.SubCategoryClother'),
        ),
    ]
