# Generated by Django 3.1.5 on 2021-01-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0004_auto_20210128_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=15)),
                ('slug', models.SlugField(blank=True, max_length=15, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.AlterField(
            model_name='clothessubcategory',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='generate_clothes.season'),
        ),
        migrations.DeleteModel(
            name='Seasons',
        ),
    ]
