# Generated by Django 3.1.5 on 2021-02-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0005_auto_20210128_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='image',
        ),
    ]
