# Generated by Django 3.1.1 on 2021-01-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0005_auto_20210104_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(max_length=255)),
                ('colour_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customstylecategory',
            name='colour',
            field=models.ManyToManyField(related_name='item', to='generate_clothes.Colour'),
        ),
    ]
