# Generated by Django 3.1.1 on 2021-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0006_auto_20210104_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstylecategory',
            name='colour',
            field=models.ManyToManyField(related_name='colour', to='generate_clothes.Colour'),
        ),
    ]
