# Generated by Django 3.1.1 on 2021-01-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_clothes', '0007_auto_20210104_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorysize',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='SizeCategory',
        ),
        migrations.DeleteModel(
            name='SubCategorySize',
        ),
    ]
